version: 2

models:
  - name: fct_transactions
    description: "不動産取引のファクトテーブル。各トランザクションにユニークなtransaction_idを付与。"
    columns:
      - name: transaction_id
        description: |
          トランザクションの連番ID（1から開始）。
          ROW_NUMBER()関数で生成され、以下の順序で確定的にソート:
          - transaction_date
          - zipcode
          - station_name
          - total_price_jpy
          - area_sq_m
          - building_structure
        tests:
          - unique
          - not_null
      
      - name: transaction_date
        description: "取引日（四半期の開始日）"
        tests:
          - not_null
      
      - name: total_price_jpy
        description: "取引価格（円）"
      
      - name: zipcode
        description: "郵便番号"

  - name: dim_addresses
    description: "住所ディメンションテーブル"
    columns:
      - name: address_id
        description: "住所の一意識別子"
        tests:
          - unique
          - not_null

  - name: dim_dates
    description: "日付ディメンションテーブル"
    columns:
      - name: date_id
        description: "日付ID（YYYYMMDD形式の整数）"
        tests:
          - unique
          - not_null